version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8080:80" # Map localhost:8080 to container's port 80
    volumes:
      - .:/var/www/html # Bind mount project folder for live edits
    restart: unless-stopped

  db:
    image: mariadb:latest # Lightweight MySQL-compatible database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnerable_db
      MYSQL_USER: vuln_user
      MYSQL_PASSWORD: vuln_password
    ports:
      - "3306:3306" # Expose database for local testing
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data: # Named volume for database persistence
